# Generated by Django 5.2.4 on 2025-12-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogpost_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='enable_code_runner',
            field=models.BooleanField(default=False, help_text='Enable interactive code execution for code blocks in this post'),
        ),
    ]
